<?php

namespace App\Services\Import\Support;

use RuntimeException;

/**
 * Resolves a coordinate to a canton code using bundled boundary polygons.
 *
 * Needed because several sources — Switzerland Tourism's attractions among them
 * — publish coordinates but no address at all, and canton is the site's primary
 * filter. Doing this locally keeps a nightly import free of per-item calls to a
 * geocoding service, which would be slow, rate limited and another thing to
 * fail on shared hosting.
 *
 * Boundaries are regenerated by database/geo/build-canton-boundaries.php.
 */
class CantonLocator
{
    /**
     * How far outside every polygon a point may sit and still be attributed to
     * the nearest canton, in degrees (~4–5 km here).
     *
     * The bundled boundaries are simplified, and they follow land borders — so
     * a lakeside landmark or a summit on the national border can fall just
     * outside every polygon. Those are real places that would otherwise import
     * with no canton and never appear under any filter. Kept deliberately
     * small: beyond this, "no canton" is the honest answer.
     */
    private const SNAP_DEGREES = 0.05;

    /** @var array<string, array{name: string, bbox: list<float>, polygons: list<list<list<list<float>>>>}>|null */
    private ?array $cantons = null;

    /**
     * @return string|null Two-letter canton code, e.g. "UR"
     */
    public function codeFor(?float $lat, ?float $lng): ?string
    {
        if ($lat === null || $lng === null) {
            return null;
        }

        foreach ($this->cantons() as $code => $canton) {
            [$minLon, $minLat, $maxLon, $maxLat] = $canton['bbox'];

            // Cheap rejection first: most cantons are ruled out by bbox alone.
            if ($lng < $minLon || $lng > $maxLon || $lat < $minLat || $lat > $maxLat) {
                continue;
            }

            foreach ($canton['polygons'] as $rings) {
                if ($this->inRing($lng, $lat, $rings[0]) && ! $this->inAnyHole($lng, $lat, $rings)) {
                    return $code;
                }
            }
        }

        return $this->nearest($lat, $lng);
    }

    /**
     * Nearest canton by distance to its boundary vertices, accepted only within
     * SNAP_DEGREES. Vertex distance slightly overestimates the true distance to
     * an edge, which errs toward returning null — the safe direction.
     */
    private function nearest(float $lat, float $lng): ?string
    {
        $best = null;
        $bestDistance = INF;
        // Longitude degrees shrink toward the poles; scale so the comparison is
        // roughly metric rather than favouring east–west neighbours.
        $cosLat = cos(deg2rad($lat));

        foreach ($this->cantons() as $code => $canton) {
            [$minLon, $minLat, $maxLon, $maxLat] = $canton['bbox'];

            if ($lng < $minLon - self::SNAP_DEGREES || $lng > $maxLon + self::SNAP_DEGREES
                || $lat < $minLat - self::SNAP_DEGREES || $lat > $maxLat + self::SNAP_DEGREES) {
                continue;
            }

            foreach ($canton['polygons'] as $rings) {
                foreach ($rings[0] as [$x, $y]) {
                    $dx = ($x - $lng) * $cosLat;
                    $dy = $y - $lat;
                    $distance = $dx * $dx + $dy * $dy;

                    if ($distance < $bestDistance) {
                        $bestDistance = $distance;
                        $best = $code;
                    }
                }
            }
        }

        return $best !== null && sqrt($bestDistance) <= self::SNAP_DEGREES ? $best : null;
    }

    /**
     * @param  list<list<list<float>>>  $rings
     */
    private function inAnyHole(float $lng, float $lat, array $rings): bool
    {
        foreach (array_slice($rings, 1) as $hole) {
            if ($this->inRing($lng, $lat, $hole)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Standard ray casting: count how many edges a ray to the east crosses.
     *
     * @param  list<list<float>>  $ring
     */
    private function inRing(float $lng, float $lat, array $ring): bool
    {
        $inside = false;
        $count = count($ring);

        for ($i = 0, $j = $count - 1; $i < $count; $j = $i++) {
            [$xi, $yi] = $ring[$i];
            [$xj, $yj] = $ring[$j];

            if (($yi > $lat) !== ($yj > $lat)
                && $lng < ($xj - $xi) * ($lat - $yi) / ($yj - $yi) + $xi) {
                $inside = ! $inside;
            }
        }

        return $inside;
    }

    /**
     * @return array<string, array{name: string, bbox: list<float>, polygons: list<list<list<list<float>>>>}>
     */
    private function cantons(): array
    {
        if ($this->cantons !== null) {
            return $this->cantons;
        }

        $path = resource_path('geo/swiss-cantons.json');

        if (! is_file($path)) {
            throw new RuntimeException("Canton boundaries missing at {$path}. Run database/geo/build-canton-boundaries.php.");
        }

        $data = json_decode(file_get_contents($path), true);

        return $this->cantons = $data['cantons'] ?? [];
    }
}
